#!/usr/bin/env python3

from optparse import OptionParser
from os.path  import isfile
from sys      import exit

# ------------------------------------------------------------------------------

parser = OptionParser("Usage: %prog <file1> <file2>")

def print_help(option, opt, value, parser):
	parser.print_help()
	exit(0)
#enddef

parser.remove_option("-h")
parser.add_option("-?", "--help", action="callback", callback=print_help)

(options, args) = parser.parse_args()

if len(args) < 2:
	parser.print_help()
	exit(1)
#endif

file1 = args[0]
file2 = args[1]

if not isfile(file1):
	print("Cannot read file %s" % file1)
	exit(1)
#endif

if not isfile(file2):
	print("Cannot read file %s" % file2)
	exit(1)
#endif

# ------------------------------------------------------------------------------

data1 = {}

with open(file1, 'r') as f:
	section = None
	
	for line in f:
		line = line.strip()

		""" Empty line """
		if not line:
			continue
		#endif

		""" Comment, skip it """
		if line[0] in [';', '#']:
			continue
		#endif

		""" Section """
		if line[0] == '[':
			section = line[1:-1]
			data1[section] = {}
			continue
		#endif

		""" Item """
		line = line.split('=')
		data1[section][line[0].strip()] = ''.join(line[1:]).strip()
	#endfor
#endwith

# ------------------------------------------------------------------------------

data2 = {}

with open(file2, 'r') as f:
	section = None

	for line in f:
		line = line.strip()

		""" Empty line """
		if not line:
			continue
		#endif

		""" Comment, skip it """
		if line[0] in [';', '#']:
			continue
		#endif

		""" Section """
		if line[0] == '[':
			section = line[1:-1]
			data2[section] = {}
			continue
		#endif

		""" Item """
		line = line.split('=')
		key = line[0].strip()
		val = ''.join(line[1:]).strip()

		if section not in data1:
			""" Missing section """
			data2[section][key] = val
		elif key not in data1[section]:
			""" Added item """
			data2[section][key] = val
		elif data1[section][key] != val:
			""" Different values """
			data2[section][key] = val
		else:
			""" Same values """
			del data1[section][key]
		#endif
	#endfor
#endwith

# ------------------------------------------------------------------------------

for section in data1:
	""" Whole section is missing """
	if section not in data2:
		print("- [%s]" % section)
		for item in  data1[section]:
			print("- %s = %s" % (item, data1[section][item]))
		#endfor
		print("")
		continue
	#endif

	""" Both sections are same """
	if not data1[section] and not data2[section]:
		continue
	#endif

	print("[%s]" % section)
	
	for item in data1[section]:
		if item not in data2[section]:
			""" Item is missing """
			print("- %s = %s" % (item, data1[section][item]))
		else:
			""" Item is not equal """
			print("< %s = %s" % (item, data1[section][item]))
			print("> %s = %s" % (item, data2[section][item]))
		#endif
	#endfor

	for item in data2[section]:
		if item not in data1[section]:
			""" Item is added """
			print("+ %s = %s" % (item, data2[section][item]))
		#endif
	#endfor

	print("")
#endfor

# ------------------------------------------------------------------------------

for section in data2:
	""" Whole section is added """
	if section not in data1:
		print("+ [%s]" % section)
		for item in  data2[section]:
			print("+ %s = %s" % (item, data2[section][item]))
		#endfor
		print("")
	#endif
#endfor
