#!/usr/bin/env python3

import random
import sys

ALLOWED_CHARS = "23456789abcdefghjknpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ"

def genPwd(length):
	return "".join(random.choice(ALLOWED_CHARS) for i in range(0, length))
#enddef

if __name__ == "__main__":
	if len(sys.argv) == 2:
		print("PWD: ", genPwd(int(sys.argv[1])))
	else:
		print("PWD:", genPwd(16))
	#endif
#endif
